### ISSUE TITLE
Use clang-format to ensure consistent style?

### ISSUE THREAD

**Issue by jserv** [azure-rtos/threadx#1]
Several Microsoft open source projects already use [clang-format](https://clang.llvm.org/docs/ClangFormat.html) to indent, such as [ONNX Runtime](https://github.com/microsoft/onnxruntime) and [STL](https://github.com/microsoft/STL). Will ThreadX project take it for consistent code style?

**Comment by jserv** [comment]
Take [samples/demo_threadx.c](https://github.com/azure-rtos/threadx/blob/master/samples/demo_threadx.c#L71) for example. The style was inconsistent.

**Comment by PProvost** [comment]
That's a good idea. We will investigate and update this issue when we've got an answer.

**Comment by PProvost** [comment]
We will continue to investigate this but can't commit to it at this point. Closing the issue for now.
