### ISSUE TITLE
POSIX?

### ISSUE THREAD

**Issue by edbek** [azure-rtos/threadx#10]
will POSIX be implemented?

**Comment by goldscott** [comment]
We do have a POSIX wrapper but haven't got it up on GitHub yet...
If you need it right away, let me know.

**Comment by edbek** [comment]
Yes, I would like to see how your POSIX is implemented. Maybe I would make any comments at this stage that would be useful to you.
Thank.

**Comment by goldscott** [comment]
Send me a message: support@expresslogic.com

**Comment by goldscott** [comment]
POSIX layer was added to ThreadX.
