### ISSUE TITLE
How does a Threadx Modules application call the libc library?

### ISSUE THREAD

**Issue by GetFreedomPro** [azure-rtos/threadx#101]
How does a Threadx Modules application call the libc library?
For example, 
you need to call the vsnprintf (), memset (), strcpy () functions
Whether to provide reference examples?

**Comment by goldscott** [comment]
We do not have any examples of a module calling these functions, nor have we tried to use the lib in a module. 

Your compiler would need to provide the position-independent code and data version of the lib.
