### ISSUE TITLE
Missing module port for RX

### ISSUE THREAD

**Issue by mransom-campbell** [azure-rtos/threadx#104]
There are no files in ports_module/ for RX processors. The documentation https://docs.microsoft.com/en-us/azure/rtos/threadx-modules/appendix#rx65n-processor mentions sample projects that do not exist.

Is the RX processor not supported by threadx modules or are those files just missing from github?

Thanks

**Comment by goldscott** [comment]
We have an older Modules port for the RX (from our Express Logic days), but this hasn't been updated for Azure RTOS yet. I am not sure when Modules for RX will be available on github.
