### ISSUE TITLE
can add cmake support for cortex_m4 gnu example

### ISSUE THREAD

**Issue by how0723** [azure-rtos/threadx#113]
can add cmake support for cortex_m4 gnu example
use gcc-arm-none-eabi toolchain

**Comment by goldscott** [comment]
Huh? We have cmake for M4 gnu: https://github.com/azure-rtos/threadx/tree/master/ports/cortex_m4/gnu

**Comment by TiejunMS** [comment]
For cmake examples, please take a look at https://github.com/azure-rtos/getting-started
