### ISSUE TITLE
Add install rules for the CMake files

### ISSUE THREAD

**Issue by pandersb** [azure-rtos/threadx#115]
The [CMake install command](https://cmake.org/cmake/help/latest/command/install.html) provides functionality which makes it possible to export the built threadx library and header files.

I am by no means no expert on CMake, but I managed to set this up with a few modifications to
* CMakeLists.txt
* common/CMakeLists.txt
* ports/cortex_a5/gnu/CMakeLists.txt

If you're interested, I'll be happy to share my modifications.

**Comment by goldscott** [comment]
Hello, sorry to tell you that currently we don't plan to maintain CMake for ports other than cortex m0/3/4/7. This may change in the future.
