### ISSUE TITLE
px_sem_open.c bug

### ISSUE THREAD

**Issue by SuWeipeng** [azure-rtos/threadx#117]
[threadx/utility/rtos_compatibility_layers/posix/px_sem_open.c](threadx/utility/rtos_compatibility_layers/posix/px_sem_open.c)

Line 113
```c
    if(semid= posix_find_sem( name))
```
`=` should be `==`
```c
    if(semid== posix_find_sem( name))
```

**Comment by SuWeipeng** [comment]
Maybe write like this is better to read:

```c
    semid = posix_find_sem( name);
    if(semid != NULL)
```

**Comment by goldscott** [comment]
This is intended behavior, and your suggestion is indeed easier to understand. We will look into improving the POSIX layer.
