### ISSUE TITLE
Win32 or Linux Port?

### ISSUE THREAD

**Issue by edbek** [azure-rtos/threadx#12]
ThreadX requires Win32 or Linux simulation ! Like for example FreeRTOS or uCOS-III.
Can we expect such an implementation for the future ?

**Comment by goldscott** [comment]
I'm not sure I understand your question. We have win32 and linux ports for ThreadX - these will be added to github soon.

**Comment by edbek** [comment]
Yes, this is the win32 and linux port.
Thank.

**Comment by goldscott** [comment]
The win32 port should be added very soon (next week or two) and linux will come after. Closing.

**Comment by rtoshub** [comment]
any news?

**Comment by goldscott** [comment]
We are about to publish a bunch of new ports, including win32 and linux, either today or early next week.

**Comment by edbek** [comment]
We wait. Thank you !

**Comment by goldscott** [comment]
Windows and Linux ports were posted. https://github.com/azure-rtos/threadx/tree/master/ports

**Comment by edbek** [comment]
Yes, we have seen and are testing. Thank you.
