### ISSUE TITLE
Substitute of std::thread detach() in ThreadX.

### ISSUE THREAD

**Issue by JesusSmarting** [azure-rtos/threadx#124]
Hi,
I want to know if there is a similar functionallity in ThreadX for detach() in std::thread.

I also want to find something familiar to a yield() function.

Thanks in advance.

**Comment by goldscott** [comment]
There is no equivalent "detach" in ThreadX. Can you explain what you are trying to do?

For yield, try https://docs.microsoft.com/en-us/azure/rtos/threadx/chapter4#tx_thread_relinquish

**Comment by JesusSmarting** [comment]
Thanks, that would do the trick.
