### ISSUE TITLE
tx_iar.c  __iar_file_Mtxinit macro reference error

### ISSUE THREAD

**Issue by weizhongbao** [azure-rtos/threadx#127]
_MAX_LOCK -> _MAX_FLOCK

**Comment by goldscott** [comment]
Did you find this as a compilation error or runtime error? IAR provides two locks, _MAX_LOCK and _MAX_FLOCK. It could also be that these locks have changed in different versions of IAR. What version are you using?

**Comment by goldscott** [comment]
Hi @weizhongbao - any response to the questions above? I'll leave this ticket open for another week. Thanks!
