### ISSUE TITLE
What is a good .gitignore file for a project that uses threadX?

### ISSUE THREAD

**Issue by KansaiUser** [azure-rtos/threadx#128]
I am currently working with a project that uses threadx and I would like to ask what is a good .gitignore file for this.

Also would it be a good idea to put the threadx code in a git submodule?

**Comment by wangwen-ms** [comment]
.gitignore is supposed to ignore intermediate files, like .o, .a, .d, which are typical intermediate files. other intermediate files depends on the develop tool you use. it is ok to use ThreadX in submodule
