### ISSUE TITLE
Calling tx_semaphore_create again after tx_semaphore_delete causes hard fault

### ISSUE THREAD

**Issue by yanglx2022** [azure-rtos/threadx#130]
![image](https://user-images.githubusercontent.com/42242348/127258734-4cac35ec-96b9-409b-8d9f-ee5caf87bf62.png)

**Comment by goldscott** [comment]
Please provide more info. Where is crash occurring? Did the delete call return successfully? Where are you calling delete and create?

**Comment by yanglx2022** [comment]
The calling process is as follows:
1. call `tx_semaphore_create()` before `tx_kernel_enter()`, it returns `TX_SUCCESS`
2. call `tx_semaphore_delete()` in a thread, it returns `TX_SUCCESS`
3. call `tx_semaphore_create()` in the same thread, crash happens

Please see the screenshot above where the crash occurred. The direct reason is that the pointer `next_semaphore = 0` was accessed.

**Comment by goldscott** [comment]
Oh, well, there's your problem - do NOT call any ThreadX APIs before calling tx_kernel_enter.
