### ISSUE TITLE
What threadx need to do when power down/up slave cores in arm Cortex-R8 SMP SOC

### ISSUE THREAD

**Issue by carll00226** [azure-rtos/threadx#131]
We are running threadx in arm cortex-r8 smp soc, when power down the slave cores ,what need to do for master core and slave cores in threadx, I only find leaveSMP in file v7.S. and also what to do when power up the slave cores? Thanks.

**Comment by goldscott** [comment]
You would have to exclude all threads/timers from executing on core X before powering down core X. Once you bring up core X, you could remove that exclusion.
