### ISSUE TITLE
Error occurs after ThreadX enables TraceX

### ISSUE THREAD

**Issue by arilink** [azure-rtos/threadx#134]
Development environment:
windows10 x64 mdk v5.34
threadx usbx 6.16
My project has entered the later stage of development and I want to try to use TraceX to optimize the program. The current project uses ThreadX+USBX. When I try to open #define TX_ENABLE_EVENT_TRACE in the tx_user.h file and compile, the following error appears. I did not find a related solution. Method May I ask what caused such a problem?

**Comment by arilink** [comment]
![tracex](https://user-images.githubusercontent.com/30901123/129160543-49fb651b-705f-422e-970e-e01e3807e11f.png)

**Comment by goldscott** [comment]
Hello @arilink - have you #defined UX_TRACE_INSERT_MACROS?

**Comment by arilink** [comment]
Is it not enough to just #define TX_ENABLE_EVENT_TRACE? I only found the use of the software in the TraceX documentation, but there is no operating method in the program

**Comment by arilink** [comment]
My operating system is windows. Do I need #defined UX_TRACE_INSERT_MACROS?

**Comment by xiaocq2001** [comment]
In USBX, trace information is generated via USBX trace functions that are enabled by UX_TRACE_INSERT_MACROS

**Comment by arilink** [comment]
Ok, I didn't find the relevant information in the document. What if it is FileX NetX?

**Comment by TiejunMS** [comment]
There is no additional macros for FileX or NetX.

**Comment by arilink** [comment]
Understand, thank you very much for your help
