### ISSUE TITLE
why do not use TX_TIMER_TICKS_PER_SECOND in tx_initialize_low_level.s to calculate timer reload count?

### ISSUE THREAD

**Issue by xiongyu0523** [azure-rtos/threadx#135]
I tried to redefine TX_TIMER_TICKS_PER_SECOND to 1000Hz in tx_user.h and it seems not working then I found the sample low level initialization file use a hardcode 100Hz.

**Comment by goldscott** [comment]
Some assemblers can't #include header files. You must redefine the value in tx_initialize_low_level.
