### ISSUE TITLE
Licensed Hardware list

### ISSUE THREAD

**Issue by josesimoes** [azure-rtos/threadx#14]
I can see on the Azure website this list of hardware partners: https://azure.microsoft.com/en-us/services/rtos/#partners
 which I presume are (will be?) the so called "pre-licensed devices". Is this correct? If yes, can the list on `LICENSED-HARDWARE.txt` be updated to reflect this?

Thanks!

**Comment by goldscott** [comment]
Hi @josesimoes - we'll be updating this list once the deals with each semi manufacturer are finalized. We're aiming for Microchip, NXP, Renesas, ST, and Qualcomm. Should be very soon!

**Comment by josesimoes** [comment]
Good to know.
Knock at TI and Nordic door too... 😉

**Comment by LP-33** [comment]
Hello,

having ThreadX and the middleware open source is great, really.
But without knowing which hardware we can use for using it freely is a real problem.

We are starting a new project based on  Kinetis K64/66 and we need to know if this MCU will be part of the pre-licensed devices.

Do you know when you could provide a preliminary list ?

Thank you.

**Comment by goldscott** [comment]
Hi @LP-33 - I feel your pain! These giant corporations and big deals seem to move very slowly. 

The Kinetis K64/66 family should be on the list once these deals are closed, but I don't know when that will happen.

**Comment by LP-33** [comment]
Hi goldscott,

ok, this is good news.
Did you plan to provide NetX/NetX-Duo ports for these MCU before that ? As you did for iMXRT1060, SAME54, STM32F746 and STM32L475?
Thank you.

**Comment by goldscott** [comment]
Hi @LP-33 - NetX and NetX Duo are available for the Cortex-M series, so they will work on the K64/66. We will not be making sample projects for every processor/dev board out there. NXP (and our other partners, ST, Microchip, etc) will likely make sample projects for their particular processors and dev boards.

**Comment by Polarisru** [comment]
Hello, how about ATSAMC21 MCUs (Cortex-M0, Microchip), will they be available for free? We are working at some new projects right now and have used FreeRTOS there, but it is still possible to change the RTOS, so we are very interested to get Azure RTOS working because of MISRA compatibility.

**Comment by JakeSays** [comment]
@Polarisru I'm a microchip customer and I was lead to believe that azure rtos is available at no cost for microchip controllers. I never pursued it though because we are also using an azure sphere which gives us license to use azure rtos on any mcu associated with the project.

**Comment by goldscott** [comment]
Hi @Polarisru - using Azure RTOS on Cortex-M devices from Microchip should be free, but we have not yet closed that deal. You are allowed to begin your development for free, so you can get started with ThreadX today.

**Comment by LP-33** [comment]
Hello,
did you plan to add a multi-core Cortex Ax(x) in the licensed list? (e.g. iMX8M Nano).
Thank you.

**Comment by goldscott** [comment]
@LP-33 - you'll have to contact the manufacturers that make those processors and ask (e.g. NXP, Renesas, etc). They choose what gets put on the list.

**Comment by Taranus** [comment]
Hello,

do you know if it is planned to add the Raspberry Pi Pico to this list?

Thank you.

**Comment by goldscott** [comment]
@Taranus - we have no plans to add RPi to the licensed hardware list.

**Comment by pnchatterji** [comment]
Hi Goldscott,

is there any possibility of using Azur RTOS on Nordic hardware in future? Is it in the works?

Otherwise, is there a possibility of using just the FileX component on top of Zephyr RTOs, for example, which is supported by Nordic? I understand FileX has a Standalone mode, so it should be possible technically. How does it look from a legal standpoint? Does one have to obtain a special license from Microsoft for this?
thanks
regards
Pashupatu

**Comment by goldscott** [comment]
@pnchatterji - we do not have any agreement with Nordic, so you would need an Azure RTOS license. 

Technically possible, though you would need to license Azure RTOS to use FileX.
