### ISSUE TITLE
How to get the percentage of CPU usage in arm Cortex-R8 system

### ISSUE THREAD

**Issue by carll00226** [azure-rtos/threadx#141]
We are using threadx in arm Cortex-R8 SMP system and want to get the percentage of CPU usage druing running timer, we port the execution_profile_kit and found it not work properly. So we want to know whether execution_profile_kit support R8 SMP? If not, any other solution to work out the problem? thanks!

**Comment by andrejm-rtos** [comment]
We are looking into the current status of the EPK for SMP ports. We will provide more information soon.

**Comment by goldscott** [comment]
There is an experimental version of the Execution Profile Kit (EPK) for SMP here: https://github.com/azure-rtos/threadx/tree/master/utility/execution_profile_kit/smp_version
