### ISSUE TITLE
motivation of arc nested logic change

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#144]
I see in release 6.1.6 you changed in arc tx_thread_context_save.s you changed logic from:

`    brne    r0, r1, __tx_thread_nested_save             ; If more interrupts, go into the nested interrupt save logic`

to:

https://github.com/azure-rtos/threadx/blob/b216ceb25e2b6ae1ea83c1ae91d114a6fc2fc4ec/ports/arc_em/metaware/src/tx_thread_context_save.s#L246-L248

what is the motivation behind this change?

**Comment by andrejm-rtos** [comment]
This has been changed to allow for a larger jump range in some situations. Depending on how ThreadX is compiled a relative branch in that location may be out of range.
