### ISSUE TITLE
How to add interface APIs for modules to call?

### ISSUE THREAD

**Issue by Femtometer** [azure-rtos/threadx#146]
For example, drivers or file system APIs.
I didn't find docs about this question in https://docs.microsoft.com/en-us/azure/rtos/threadx-modules/

**Comment by goldscott** [comment]
We do not yet have FileX integrated with Modules. You can, however, add your own kernel calls using the https://docs.microsoft.com/en-us/azure/rtos/threadx-modules/chapter4#txm_module_application_request API.
You can add your own code to this function: https://github.com/azure-rtos/threadx/blob/master/common_modules/module_manager/src/txm_module_manager_application_request.c
