### ISSUE TITLE
Timer interrupt enable before init finishes

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#147]
I see in gnu port you initialize the timer interrupt just after all initialization is finished:
https://github.com/azure-rtos/threadx/blob/b216ceb25e2b6ae1ea83c1ae91d114a6fc2fc4ec/ports/linux/gnu/inc/tx_port.h#L369

but in arc port (and probably in more ports?) you are enabling timer interrupts before initialization finishes:
https://github.com/azure-rtos/threadx/blob/b216ceb25e2b6ae1ea83c1ae91d114a6fc2fc4ec/ports/arc_em/metaware/example_build/sample_threadx/tx_initialize_low_level.s#L150-L151
This may cause problem in case the timer will expire before initialization will finish (got not OS related interrupt that slowed down the system for example)

**Comment by andrejm-rtos** [comment]
This has been updated and it will be available in the next release
