### ISSUE TITLE
How to use TX_LOW_POWER in arm cortex-R SMP system

### ISSUE THREAD

**Issue by carll00226** [azure-rtos/threadx#154]
Hi :
    I notice that tx_low_power utility has been used in file tx_thread_schedule.S for arm cortex-M ,  then how to use it in cortex-R SMP system? Maybe we can create a lowest prority idle thread and call tx_low_power_enter in it? Would you please give me some advices, thanks a lot.

**Comment by goldscott** [comment]
The low power code has **not** been designed for the SMP ports. It will not work.
