### ISSUE TITLE
Cortex-M port: _tx_thread_system_return_inline lacks volatile qualifier

### ISSUE THREAD

**Issue by udoe** [azure-rtos/threadx#167]
Hi Scott,

The function _tx_thread_system_return_inline in ports\cortex_m7\gnu\inc\tx_port.h sets PendSV:
    `*((ULONG *) 0xE000ED04) = ((ULONG) 0x10000000);`

This should be :
    `*((volatile ULONG *) 0xE000ED04) = ((ULONG) 0x10000000);`

Regards,
Udo

**Comment by goldscott** [comment]
Thank you! We will add the volatile keyword in the next release.

**Comment by goldscott** [comment]
This has been fixed in 6.1.11: https://github.com/azure-rtos/threadx/blob/master/ports/cortex_m7/gnu/inc/tx_port.h
