### ISSUE TITLE
Xtensa Port: Misnamed symbols

### ISSUE THREAD

**Issue by cbezault** [azure-rtos/threadx#169]
https://github.com/azure-rtos/threadx/blob/11303a0e1bb184c87ef267b582e5272054006edc/ports/xtensa/xcc/inc/xtensa_timer.h#L149-L152

Shouldn't the symbols in the above lines all have a leading `_`?

**Comment by goldscott** [comment]
This is not ThreadX code. This is driver code from Xtensa.

**Comment by cbezault** [comment]
Okay then these symbols aren't referenced correctly here:
https://github.com/azure-rtos/threadx/blob/11303a0e1bb184c87ef267b582e5272054006edc/ports/xtensa/xcc/src/tx_initialize_low_level.c#L156-L165

**Comment by cbezault** [comment]
Sure but where is `tx_initialize_low_level.c` supposed to see the declarations for them?
I'm having a link compilation issue when I define `XT_BOARD`.

**Comment by goldscott** [comment]
What compilation issue are you seeing when you define XT_BOARD?

**Comment by cbezault** [comment]
```
FAILED: src/externs/threadx/CMakeFiles/ThreadX.dir/src/ports/xtensa/xcc/src/tx_initialize_low_level.c.obj
../../../src/externs/threadx/src/ports/xtensa/xcc/src/tx_initialize_low_level.c:157:5: error: implicit declaration of function '_xt_tick_divisor_init' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
../../../src/externs/threadx/src/ports/xtensa/xcc/src/tx_initialize_low_level.c:157:5: error: this function declaration is not a prototype [-Werror,-Wstrict-prototypes]
src/ctl/../../../src/externs/threadx/src/ports/xtensa/xcc/src/tx_initialize_low_level.c:164:39: error: use of undeclared identifier '_xt_tick_divisor'; did you mean 'xt_tick_divisor'?
ninja: build stopped: subcommand failed
```

**Comment by goldscott** [comment]
Thanks for those additional details! We'll get this fixed in the next release.
