### ISSUE TITLE
Are there plans to open source the TRICORE(Infineon) SMP version? 

### ISSUE THREAD

**Issue by snikeguo** [azure-rtos/threadx#170]
SMP ..

**Comment by goldscott** [comment]
Hello. I don't believe we have an SMP version of ThreadX available for the Tricore.

**Comment by snikeguo** [comment]
> Hello. I don't believe we have an SMP version of ThreadX available for the Tricore.

OK~ Do you have any plans to port the SMP version of Threadx to TRICORE?  thanks

**Comment by photex** [comment]
I've happened across this issue while searching for an RTOS for the TC377TX (Automotive Secure Gateway).
Would love to know if anything came from your discussions.
