### ISSUE TITLE
_tx_event_flags_set preempt_check question

### ISSUE THREAD

**Issue by arm7star** [azure-rtos/threadx#175]
when TX_NOT_INTERRUPTABLE is not defined. _tx_event_flags_set just disables preempt and preempt_check only is set to TX_TRUE when flags_satisfied is not zero, but the ISR may resume some higher thread.
If ISR resume higher threead, does _tx_thread_system_preempt_check need to be called?

**Comment by goldscott** [comment]
Good find. We are looking into this.

**Comment by goldscott** [comment]
Hi @arm7star - we have confirmed this is a bug and we have fixed it. The updated code will be available in our next release. Thank you! I'll keep this ticket open and close it once the release is made.

**Comment by arm7star** [comment]
OK. Thank you!
