### ISSUE TITLE
Could I know if there is any settings that I missed for executing sample threadx?

### ISSUE THREAD

**Issue by chojpsh1** [azure-rtos/threadx#180]
Hello, I have a question about executing sample threadx on Arm Development Studio IDE with FVP_Cortex_A55.

I opened the example_build project which is located at ports_smp/cortex_a55_smp/gnu/ and built the tx and sample_threadx project. So, I saw the sample_threadx.axf file was saved in Debug directory.
I created the debug model connection which's target is FVP_Cortex_A55x1 and connected to sample_threadx.axf but, any threads didn't execute and loop in _tx_initialize_kernel_enter. 
(System Timer Thread's state : SUSPENDED and thread 0~7 state : READY)

Is there a process or settings that I missed in executing the thread?

**Comment by carll00226** [comment]
your target is cortex_a55*1, it's single core, not smp, you should port form ports/, not ports_smp/.

**Comment by chojpsh1** [comment]
Thank you for reply @carll00226 :)
I modify the target FVP_cortex_a55*4 and check the TX_THREAD_SMP_MAX_CORES is 4.
But, threads still don't execute (System Timer Thread's state : SUSPENDED and thread 0~3 state : READY) and loop in _tx_initialize_kerenl_enter.

**Comment by carll00226** [comment]
I think it is a coherence issue，core0 is waiting for other cores to be ready. you can check your setting about cache, mmu, scu...which do the coherence  job.

**Comment by chojpsh1** [comment]
It's resolved by defining TX_ARMV8_2
