### ISSUE TITLE
Incorrect preprocessor macro in tx_thread_smp_protect.S

### ISSUE THREAD

**Issue by vks3** [azure-rtos/threadx#186]
In tx_thread_smp_protect.S, for the a7-smp port (probably in others too), the following line has an incorrect preprocessor leading to some critical code being excluded and causing deadlocks and random crashes.

https://github.com/azure-rtos/threadx/blob/f851772ce02633f62d2fb4d043766ea54268684f/ports_smp/cortex_a7_smp/gnu/src/tx_thread_smp_protect.S#L101

Instead of #else, ELSE is used which is ignored by the compiler if TX_ENABLE_FIQ_SUPPORT is not set.

The same issue is repeated here too -
https://github.com/azure-rtos/threadx/blob/f851772ce02633f62d2fb4d043766ea54268684f/ports_smp/cortex_a7_smp/gnu/src/tx_thread_smp_protect.S#L252

This at least solved my present issue of CPU getting deadlocked and no threads being scheduled (issue #179).

**Comment by goldscott** [comment]
Hi @vks3 - thank you for finding this! We have ThreadX version 6.1.11 coming out next week and can't make any more changes to it right now, so this will be fixed in 6.1.12.

**Comment by goldscott** [comment]
Update: it looks like this is only in the Cortex-A7 SMP file that you mention. I did not find it anywhere else. I'll keep this ticket open and close it once version 6.1.12 has been released.

**Comment by goldscott** [comment]
This was fixed in 6.1.12 release.

https://github.com/azure-rtos/threadx/blob/8c3c08f10826c4d5332a6d8e2fdf014b793a456a/ports_smp/cortex_a7_smp/gnu/src/tx_thread_smp_protect.S#L103

https://github.com/azure-rtos/threadx/blob/8c3c08f10826c4d5332a6d8e2fdf014b793a456a/ports_smp/cortex_a7_smp/gnu/src/tx_thread_smp_protect.S#L254
