### ISSUE TITLE
Error while running threadx app on zynq 7000 series board

### ISSUE THREAD

**Issue by savansanghavi** [azure-rtos/threadx#188]
i am trying to run the threadx example app with zynq 7000 series board.
with this i am using tx_initialize_low_level.S from the this repo.
In the run time app is going in the undefined exception.

Can anyone help with this?
Do i have to make changes in the linker script or low level initialization file?

Thanks in advance.

**Comment by goldscott** [comment]
Please email azure-rtos-support@microsoft.com and I'll send you a demo for the ZC702 board.
