### ISSUE TITLE
how to build cortex-a7 port?

### ISSUE THREAD

**Issue by 13824125580** [azure-rtos/threadx#19]
when i config the cortex_a7 port like your readme show, just replease the m4 to a7
 cmake -Bbuild -DCMAKE_TOOLCHAIN_FILE=cmake/cortex_a7.cmake -GNinja .
it report failure for this:
ke-3.15/Modules/CMakeDetermineSystem.cmake:99 (message):
  Could not find toolchain file: cmake/cortex_a7.cmake
Call Stack (most recent call first):
  CMakeLists.txt:4 (project)

CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_ASM_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!

so, could you show me how to compile the a7 port?

**Comment by goldscott** [comment]
Hi @13824125580 - we didn't make a CMakeList.txt file for the A7 port (you can make one by looking at e.g. the Cortex-M7 port). 
Instead, we provided an example_build directory with batch files to build the A7 port (you'll have to make your own makefile): https://github.com/azure-rtos/threadx/tree/master/ports/cortex_a7/gnu/example_build

If there is user interest, we'll continue to make CMake files for all the GNU ports. Let us know.
