### ISSUE TITLE
A78AE port

### ISSUE THREAD

**Issue by Hunter-Phipps** [azure-rtos/threadx#204]
Are there any plans to port Azure RTOS to ARM Cortex-A78AE?

**Comment by goldscott** [comment]
Cortex-A78AE is an ARMv8-A core. All of our ARMv8-A ports (e.g. A55, A77, etc.) are derived from one common ARMv8-A port. Although there is not "official" A78AE port, you can use one of the other ports (e.g. A77) and it should work just fine.

**Comment by goldscott** [comment]
Let us know if you have other questions, otherwise I'll close this issue. Feel free to re-open.

**Comment by Hunter-Phipps** [comment]
Has anyone tried running Azure RTOS on the Nvidia AGX Orin A78AE processor?

**Comment by goldscott** [comment]
Hi @Hunter-Phipps - not that I am aware of. Nobody on the RTOS team has tried on that processor.
