### ISSUE TITLE
File names overlaping 

### ISSUE THREAD

**Issue by josesimoes** [azure-rtos/threadx#205]
Just got this when checking out the repo on a Windows machine:

![image](https://user-images.githubusercontent.com/1881520/181771077-4a7244aa-05d4-4663-9d69-c9ad2ccfffa5.png)

And I can confirm that (obviously) I only have one file `cortexm_crt0.S`

**Comment by goldscott** [comment]
Thanks! This was fixed here: https://github.com/azure-rtos/threadx/pull/206
