### ISSUE TITLE
Cortex-R52/ARMv8-R arch support

### ISSUE THREAD

**Issue by chennakeshavaSoC** [azure-rtos/threadx#220]
I read some where about availability of ThreadX support for R52/ARMv8-R arch, but could not find in main branch. Do we have any plans to support for Cortex-R52 architecture (ex. Renesas rzn2l-rsk)?

**Comment by goldscott** [comment]
We haven't had any demand for the ARMv8-R arch yet, but it is on our roadmap, though we don't have a timeframe.

**Comment by thejpster** [comment]
Such a port would be very useful to me, and some of my clients.

Support already exists for Armv8-R AArch32 in Zephyr and NuttX, as far as I can tell.
