### ISSUE TITLE
New licensed hardware

### ISSUE THREAD

**Issue by FernanGallego** [azure-rtos/threadx#223]
Is there any plan to add more hardware in the LICENSED-HARDWARE list? 
It was said to be more coming soon, but there has not been an update sin April 2021. I'm planning o a new HW design and that would be a great information to know.

Kind regards,

**Comment by goldscott** [comment]
We don't have any new partners/hardware yet. What MCUs are you considering?

**Comment by FernanGallego** [comment]
Thanks for your response Scott. We are testing some ARM from NXP. We are
actually working with the IMX8MPlus eval kit. But we could use some other
ARM as long as it has PCIExpress ports.

Kind regards,

*Fernando Gallego Vilaltella*

Operations and Innovation Manager



M  (+34) 654 93 41 54

T  (+34) 932 98 86 50

E  fernan.gallego @ lanaccess. com



LANACCESS <https://www.lanaccess.com/> | + segura + inteligente + rentable

**Comment by goldscott** [comment]
I suggest you reach out to NXP to see if they are considering adding the iMX8 to the licensed hardware list. Offhand, I don't know what currently licensed hardware has PCIE ports.
