### ISSUE TITLE
tx_thread_suspend make endless loop

### ISSUE THREAD

**Issue by zhenbin-lin** [azure-rtos/threadx#233]
**Describe the bug**
Hi developers:
  Today, I want to implement a delay function. such as delayMS. When I use the function tx_thread_sleep, I meet a bug. My programe only one thread, when this thread into sleep, the system will alway in PenSV_Handler that make SysTick_Handler would not be executed. So the procedure was alway loop in __tx_ts_wait.
  That maybe can fix, I could use interrupt nesting sloving the issue. Is that possibly move __tx_ts_wait out from interrupt context?

Please also mention any information which could help others to understand
the problem you're facing:
- MCU：STM32F103ZET6
- v6.2.0_rel
- MDK326

**Comment by zhenbin-lin** [comment]
: ) sorry, my english is pool.

**Comment by goldscott** [comment]
Hello, you need to configure your interrupt priorities so that the systick interrupt priority is higher than the pendsv priority, as we do in tx_initialize_low_level: https://github.com/azure-rtos/threadx/blob/master/ports/cortex_m3/gnu/example_build/tx_initialize_low_level.S#L131-L132

**Comment by zhenbin-lin** [comment]
> Hello, you need to configure your interrupt priorities so that the systick interrupt priority is higher than the pendsv priority, as we do in tx_initialize_low_level: https://github.com/azure-rtos/threadx/blob/master/ports/cortex_m3/gnu/example_build/tx_initialize_low_level.S#L131-L132

Thank you for your guidance!!! I have found the problem out my program and gained a deeper understanding of interrupts. Sorry for taking up your time.
