### ISSUE TITLE
TraceX portability/other trace supports

### ISSUE THREAD

**Issue by Jasinsky** [azure-rtos/threadx#235]
Hello ThreadX maintainers!

This is not a feature request per se - but question if:
- Are there any plans to support TraceX visualizer on OSes other than Windows?
- Any other trace supporting tools? e.g. SEGGER SysVIEW

Thanks in advance,
Daniel

**Comment by TiejunMS** [comment]
@Jasinsky , just so you know we don't have any plans to support other OSes. AFAIK, there is no special support to other trace tools.

**Comment by Jasinsky** [comment]
@TiejunMS  - thanks for the prompt response. Closing.
