### ISSUE TITLE
Are adaptation layers SIL-4 precertified?

### ISSUE THREAD

**Issue by sdelcore** [azure-rtos/threadx#238]
Sorry if this is noted in the documents, but I can't seem to find it anywhere. Are the adaptation layers pre-certified? Specifically the POSIX layer on ThreadX, and the BSD layer on NetXDuo.

**Comment by TiejunMS** [comment]
Hi @sdelcore , adaptation layers are not part of certification.

**Comment by TiejunMS** [comment]
Closing
