### ISSUE TITLE
any way to run on qemu emulator on target cortex-A port? such as cortex-a7 or else?

### ISSUE THREAD

**Issue by 13824125580** [azure-rtos/threadx#24]
HI folks:
   i compile ok and gennerante the elf result object on cortex-a sample project, and the next i want to do to run it, firstly i want to run it on qemu first, so could you show me anyway i can do this on qemu to test my compile result?

thank you!

**Comment by goldscott** [comment]
Hi @13824125580 - We don’t have any examples or experience running our generic ThreadX for Cortex-A7 port on QEMU. If you happen to make any headway here, please let us know.  Also worth mentioning is that the major ARM tools (IAR, ARM, etc.) have instruction set simulators that can execute this ELF image. 
You should be able to run the ThreadX demonstration in QEMU just like any other application.
