### ISSUE TITLE
When add two unsigned long long fields to the tx_thread structure，then create some threads, run some time, The system（cortex-m4） will enter a hardware failure.

### ISSUE THREAD

**Issue by alwdev2019** [azure-rtos/threadx#259]
**Describe the bug**
hardware environment: cortex-m4
When add two unsigned long long fields to the tx_thread structure，then create some threads, run some time, The system（cortex-m4） will enter a hardware failure.
A thread uses the function vsnprintf to format a variable of type double into a buffer。but this thread formats variables of other types, such as int, there is  hardware failure in the system。

Please also mention any information which could help others to understand
the problem you're facing:
- What target device are you using?: cortex-m4
- Which version of Azure RTOS?: 6.1.9
- What toolchain and environment? : gcc,cortex-m4
- What have you tried to diagnose or workaround this issue?
- the caller of  the function hardfault_handler is _tx_thread_schedule.
- the  procedure go to some abnormal address like 0xFFFFFFF1
- when i change the type of the fields to unsigned long ,the bug will disappear.
registers infor
![resisters](https://user-images.githubusercontent.com/46637936/236592260-d72449ab-bbef-4a1c-bea7-502450cd4046.png)

**To Reproduce**
1. Build my project in IAR Workbench.
1. See error

**Expected behavior**

**Impact**
What impact does this issue have on your progress (e.g., annoyance, showstopper)

**Logs and console output**
If applicable, add console logs or other types of debug information like Wireshark capture as `.zip` file.

**Additional context**

**Comment by TiejunMS** [comment]
Closing.
