### ISSUE TITLE
why the _tx_thread_rquilish did not do the " TX_THREAD_SYSTEM_RETURN_CHECK(combined_flags)" check before enter the scheduler?

### ISSUE THREAD

**Issue by 13824125580** [azure-rtos/threadx#26]
HI folks:

   on many occasions before enter the scheduler, the threadx software flow would involke the " TX_THREAD_SYSTEM_RETURN_CHECK(combined_flags)" the check whether it is feasible to call _tx_thread_system_return() to 
get the scheduler service.
but it seems  the _tx_thread_relinquish is a exception and ony one exception, it just do the _tx_thread_system_return without any check.

is this robust if user application call disable the  preempt before calling the _tx_thread_relinquish ? can this be a problem?

thank you!

**Comment by goldscott** [comment]
Hello @13824125580 - The answer for this is that tx_thread_relinquish is only allowed from a thread context and always overrides any preemption-threshold (preemption disable) setting, per ThreadX User Guide: https://docs.microsoft.com/en-us/azure/rtos/threadx/chapter4#tx_thread_relinquish
