### ISSUE TITLE
Does threadx support dynamic power off one or more cores in SMP system? 

### ISSUE THREAD

**Issue by carll00226** [azure-rtos/threadx#262]
HI, all:
     We are using threadx in a SMP * 4 system and  we want to power off 1 , 2 or 3 cores when necessary, what need to do for threadx? I find the macro TX_THREAD_SMP_DYNAMIC_CORE_MAX,  but it seems threadx do not change the value of _tx_thread_smp_max_cores, so what is it used for ?

**Comment by TiejunMS** [comment]
For ThreadX, you will need to exclude the cores for every thread by `tx_thread_smp_core_exclude()`. And also exclude those cores for timer by `tx_thread_smp_core_get()`.

**Comment by carll00226** [comment]
Hi，TiejunMS:
    What's the meaning of  "exclude those cores for timer by tx_thread_smp_core_get()"?  tx_thread_smp_core_get just get the core id.  Do you mean the tick timer? the core which start the tick timer will not be powered down until the cluster powered off.

**Comment by carll00226** [comment]
core0 start the tick timer and decide which cores should be power down at a certain time. Whether the other cores must be idle when core0 exclude these cores for every thread and then power them down ？ If core0 want to power down a core at any time, send a message to notify the core, and the core is executing a task at this time, how to save the context and exclude the task from this core ?

**Comment by TiejunMS** [comment]
Sorry about the typo. The API to exclude timer cores should be `tx_timer_smp_core_exclude`.

**Comment by TiejunMS** [comment]
Closing
