### ISSUE TITLE
How to port threadx to a real chip?

### ISSUE THREAD

**Issue by zzzh** [azure-rtos/threadx#28]
Hello,

I was trying to make threadx work on a board with the chip of STM32F407ZG（which is a Cortex-M4 chip）, my dev-tool is keil's mdk-arm, debuger is j-link.

Seems it's not so easy as the readme describe, j-link says it need to know the real chip type number to download the image, after set that, I got error messages as below:
 
No Algorithm found for: 00000000H - 00002043H
Erase skipped!
Error: Flash Download failed  -  "Cortex-M4"

So, how to fix that?

**Comment by goldscott** [comment]
Hi @zzzh - we create release examples that can run in common simulators. Every chip has a different memory map, so you'll need the right linker file for your chip, as well as select your chip in your debugger.
