### ISSUE TITLE
SMP code for MIPS CPU not found

### ISSUE THREAD

**Issue by bigfeng12** [azure-rtos/threadx#29]
The THREADX official documentation shows that threadx could support MIPS cpu， but there is no MIPS cpu source code in ports and smp directories at all. So the threadx could really support MIPS cpu and it`s SMP？ where could I get support？

**Comment by goldscott** [comment]
Hello @bigfeng12 - we are still working on getting all of the ThreadX ports up on github. We do have MIPS and MIPS SMP, just not on github yet. Can you send us a message here https://rtos.com/contact/ with your request?
