### ISSUE TITLE
building threadx for mingw

### ISSUE THREAD

**Issue by mendez23** [azure-rtos/threadx#323]
Hello!

I'm having trouble building sample_threadx app under mingw/ucrt64 - is there a recommended way of building it? I have tried to use both linux.cmake/win32.cmake as CMAKE_TOOLCHAIN_FILE argument with no avail.

threadx library builds fine but the build fails during sample_threadx executable, with complaints about missing windows system libraries

Would appreciate your help! Thank you

**Comment by TiejunMS** [comment]
Hi I never succeeded building ThreadX for Linux port in MinGW. Recommend building it in WSL2 on Windows.

**Comment by mendez23** [comment]
thank you - my experience was not unusual after all :)
