### ISSUE TITLE
Plugin for Ozone debugger

### ISSUE THREAD

**Issue by mishka88ru** [azure-rtos/threadx#33]
Hello!  
SEGGER J-Links are popular and Ozone itself is free, so I think [plugin for Ozone debugger](https://www.segger.com/products/development-tools/ozone-j-link-debugger/technology/rtos-awareness/) can become an important part of ecosystem around Azure RTOS...

**Comment by goldscott** [comment]
Hello @mishka88ru - typically, the tool makers develop the RTOS plug-ins, not us. For example, IAR, Green Hills, etc. all have created their own ThreadX plugins. Hopefully Segger will do the same.
