### ISSUE TITLE
how to enable tickless?

### ISSUE THREAD

**Issue by zhangshengping** [azure-rtos/threadx#35]
is threadx support tickless mode?

**Comment by goldscott** [comment]
Do you mean a tickless idle? If so, I can send you some code for that (please send me your email address). If you mean tickless all the time, yes, #define TX_NO_TIMER and rebuild - but note that any sleep, API timeouts, time slicing, and application timers are not available.

**Comment by goldscott** [comment]
I'll go ahead and close this ticket - feel free to re-open if you have more questions.
