### ISSUE TITLE
is malloc() and free() thread-safe on threadx

### ISSUE THREAD

**Issue by killeder** [azure-rtos/threadx#42]
is malloc() and free() thread-safe on threadx

**Comment by goldscott** [comment]
The ThreadX kernel does not use the heap, but users are free to use the heap if they want. You need to make sure you are using thread-safe versions of malloc and free (or use a mutex/semaphore for protection). Note that ThreadX provides tx_byte_pool and tx_block_pool for memory. These are thread-safe.
