### ISSUE TITLE
adding realloc functionality to byte pool

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#43]
When linking libraries with RTOS project, one need to provide allocation functions. if he decide to use byte pool for that, the creation of free, malloc and calloc is easy.
but realloc is more problematic - with little digging in to how block of byte pool is built he can get the size of the block and do malloc-memcpy-free, but this approach fragments the pool and taking time, I want to know if you are planing to support good realloc (resizing the block if can)?

**Comment by goldscott** [comment]
Hi @amgross, I don't see much use or need for this function in embedded systems. We don't have any plans to implement realloc.
