### ISSUE TITLE
Name clash between tx_thread_entry_exit_notify function pointer and define

### ISSUE THREAD

**Issue by inok16** [azure-rtos/threadx#46]
Hi,

my goal is to implement a CPU consumption profiler on a per-thread basis on a Cortex-M4 hardware (GCC).
My thought was to implement _tx_execution_thread_exit and _tx_execution_thread_enter by myself (is there any documentation about that? i.e. function signatures, examples?) There I wanted to use tx_thread_identify to gain access to the thread control block of the current thread to be able to trigger the tx_thread_entry_exit_notify callback of the current thread by passing TX_THREAD_ENTER and TX_THREAD_EXIT, respectively. It will trigger the entry/exit callback, that must be registered with tx_thread_entry_exit_notify, not only at enter- and exit-event, but also upon context switch. This is my basic intention.

Therefore I had to include tx_api.h. In that header file, there is the following define:
#define tx_thread_entry_exit_notify                 _txe_thread_entry_exit_notify

Now, the compiler complains about CurrentThread->tx_thread_entry_exit_notify, which will result in CurrentThread->_txe_thread_entry_exit_notify, that does not exist.

I know about the TX_SOURCE_CODE define. But is it really desired?

Best regards

**Comment by goldscott** [comment]
Hello @inok16 - I can send you our "profile execution kit" which does exactly what you want - measure performance of threads, interrupts, and idle time. Email us at support@expresslogic.com - this is our old support email, but it'll still work.
