### ISSUE TITLE
No makefile under threadx/ports_smp/linux/gnu/example_build?

### ISSUE THREAD

**Issue by onerebos** [azure-rtos/threadx#47]
Hi Admin,

It looks like there is no Makefile uploaded for threadx/ports_smp/linux/gnu/example_build?

Cheers.

**Comment by onerebos** [comment]
Some update, I just copied Makefile from ports/linux/gnu/example_build and changed COMMON_PATH to common_smp. It just worked...

**Comment by goldscott** [comment]
Thanks! We'll fix this in the next release.
