### ISSUE TITLE
No source or install for TraceX

### ISSUE THREAD

**Issue by BarryNolte** [azure-rtos/threadx#5]
Not sure where to put this bug, but there is no repository for TraceX, and the online docs  at: 

https://docs.microsoft.com/en-us/azure/rtos/tracex/  The "Download TraceX leads to a 404 error.

**Comment by PProvost** [comment]
The installer for TraceX is getting the finishing touches and will be posted as soon as possible.

In the meantime, we've updated the aka.ms link so it doesn't 404.

Once it has been posted, you will be able to find it under Releases in this repository, or via this link:

https://aka.ms/azrtos-tracex-installer
