### ISSUE TITLE
unused line at arc-em porting

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#52]
hi, the line below is doing nothing (except of using processor time and code space), as no one is doing something with the data loaded to %4. 
https://github.com/azure-rtos/threadx/blob/609c75a2e51735fa3ad894e0caef595ab71ba6c9/ports/arc_em/metaware/src/tx_timer_interrupt.s#L190

I am not sure if the right way is to remove this line (and the context_restore function do what needed when preempt_disable is on) or need to do something with this value

**Comment by goldscott** [comment]
Hi @amgross - you are correct. This line is not needed. I'll remove it for the next release.
