### ISSUE TITLE
Plan for SMP support?

### ISSUE THREAD

**Issue by hungys** [azure-rtos/threadx#6]
As I know, ThreadX had been added SMP support long time ago, but it seems that multicore SMP feature was not included in Azure RTOS release, any plan on this?

**Comment by yuxin-azrtos** [comment]
We will SMP version released on Github soon. Is there a particular processor/toolchain you are looking for?

**Comment by mfkiwl** [comment]
How about Rockchip's RK3308? It has 4 cortex A-35 cores and doesn't have GPU, so easier to port.

**Comment by yuxin-azrtos** [comment]
@mfkiwl We do plan to support A-35 SMP using ARM and GCC toolchain.  It will be available on GH later this year.

**Comment by mfkiwl** [comment]
> @mfkiwl We do plan to support A-35 SMP using ARM and GCC toolchain. It will be available on GH later this year.

Good news for me. Can't wait to see it happen!

**Comment by hungys** [comment]
@yuxin-azrtos Any plan for MIPS or RISC-V processor support? Thanks.

**Comment by mycan12345** [comment]
> How about Rockchip's RK3308? It has 4 cortex A-35 cores and doesn't have GPU, so easier to port.

Hi, have you port threadx to rk3308?

**Comment by goldscott** [comment]
@mycan12345 A35 is here: https://github.com/azure-rtos/threadx/tree/master/ports_smp/cortex_a35_smp
