### ISSUE TITLE
Failed to build

### ISSUE THREAD

**Issue by simon13579** [azure-rtos/threadx#64]
Hello,

I follow the README to build the sample, but it report the error when I execute the command "cmake --build ./build", could you please help me check? Thanks!

Thanks,
Simon
![Screenshot from 2020-12-28 06-10-02](https://user-images.githubusercontent.com/38149116/103219858-c589ee00-4959-11eb-9e44-5d99eb7dad46.png)

**Comment by TiejunMS** [comment]
I guess the cmake version is less than 3.13 so `-B` option does not work. You can use these commands instead. In `threadx` folder, run
``` shell
mkdir -p build
cd build
cmake -DCMAKE_TOOLCHAIN_FILE=cmake/cortex_m4.cmake -GNinja ..
cmake --build .
```

@ryanwinter , do you think we should require a minimal cmake version of 3.13 or update the readme instructions?

**Comment by goldscott** [comment]
Hi @simon13579 - have you been able to build after using @TiejunMS suggestion?
Either update your cmake or use the commands above. 

Thanks!

**Comment by simon13579** [comment]
Hello @goldscott @TiejunMS ,

I am able to bulid after following @TiejunMS  suggestion. Thanks!

Best Regards,
Simon
