### ISSUE TITLE
don't allocate space to filex when not using it

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#65]
can you add some flag such as TXM_MODULE_ENABLE_FILEX that you have in modules, and add this pointer to the thread struct just when it defined?
https://github.com/azure-rtos/threadx/blob/b0e9b132b59ab703f19b4588ed785c9c8e7a1072/common/inc/tx_api.h#L422
I suppose that most of threadx user don't use filex

**Comment by goldscott** [comment]
Hi @amgross - it is probably easier to waste a pointer in each thread struct rather than having the user #define some symbol to enable FileX and rebuild the ThreadX library. I'll discuss with the team and get back to you.

**Comment by yuxin-azrtos** [comment]
@amgross As this request is now tracked internally, I am closing the issue. Feel free to reopen it if you have additional thoughts on this. Thanks!

**Comment by amgross** [comment]
thanks for implementing :)
