### ISSUE TITLE
CMAKE_SYSTEM_PROCESSOR not right?

### ISSUE THREAD

**Issue by JarvisXing** [azure-rtos/threadx#7]
In cortex_m0.cmake & cortex_m3.cmake
`set(CMAKE_SYSTEM_PROCESSOR cortex-m4)` 
in cortex_m0.cmake, `cortex-m4` -> `cortex-m0`  ?
in cortex_m3, cmake, `cortex-m4` -> `cortex-m3`  ?

**Comment by PProvost** [comment]
You are correct, but that variable isn't used in the builds, so it shouldn't affect anything to leave it alone. I'll update them shortly to avoid future confusion.

**Comment by PProvost** [comment]
Just pushed these edits. Thanks!
