### ISSUE TITLE
Custom events configurtion with TraceX not possible

### ISSUE THREAD

**Issue by fzawadiak** [azure-rtos/threadx#74]
Don't know where else to put it. TraceX is downloadable now only from the Store. Documentation about defining custom events is wrong, there is no "installation directory" with eltrxcustom.trxc etc. Kind of severly limiting usability of ThreadX. Preferably file would be read from project directory, not installation directory.

**Comment by yuxin-azrtos** [comment]
@fzawadiak thank you for the feedback.  We will review it and get it back to you.

**Comment by goldscott** [comment]
Hi @fzawadiak - in our transition to using the Store, we didn't account for the lack of access to the install directory when trying to build custom events. I believe we are changing this to allow you to select a folder to use for custom events. Stay tuned for TraceX updates.

**Comment by jdeere5220** [comment]
@fzawadiak we have published an update to the Microsoft Store that should correct the problem. Your TraceX should automatically update to version 6.1.4.0, usually within 24 hours. Once your app has been updated, when you first run TraceX you should be prompted to choose a local folder for your example trace data files and your custom event specification file.

**Comment by goldscott** [comment]
Thanks @jdeere5220 
I'll close this ticket now.
