### ISSUE TITLE
Why each module thread need TXM_MODULE_THREAD_ENTRY_INFO on its stack?

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#77]
Hi

As far as I see, on each module thread stack you are putting copy of TXM_MODULE_THREAD_ENTRY_INFO.

I don't understand why can't you put it just on the first thread stack and give to each other thread pointer to it (anyway, I think you are storing in the global _txm_module_entry_info just pointer to the first thread instance).

**Comment by goldscott** [comment]
Hi @amgross 

Each thread's entry function and parameter is in that struct, as well as the optional entry_exit_notify function. So each thread must have that struct.
