### ISSUE TITLE
CMake build and TX_ENABLE_FPU_SUPPORT placement

### ISSUE THREAD

**Issue by fzawadiak** [azure-rtos/threadx#79]
It is not possible to define TX_ENABLE_FPU_SUPPORT in tx_user.h which would be a perfect place for it.
What is the recommended way to set it with external CMake build?

**Comment by fzawadiak** [comment]
OK, tx-user.h is not a good place, adding to compiler flags...

**Comment by goldscott** [comment]
Needs to be defined in assembly files, which don't naturally include .h files.

**Comment by hwmaier** [comment]
Sorry to re-open this, but the assembly files referencing TX_ENABLE_FPU_SUPPORT are .S files which per definition are passed through the pre-processor so they could be changed to #include tx_user.h.
