### ISSUE TITLE
_tx_mutex_priority_change preemption doubt

### ISSUE THREAD

**Issue by arm7star** [azure-rtos/threadx#89]
https://github.com/azure-rtos/threadx/blob/master/common/src/tx_mutex_priority_change.c line 318~320
                            /* Remember that this thread was preempted by a thread above the thread's threshold.  */
                            TX_MOD32_BIT_SET(next_execute_ptr -> tx_thread_priority, priority_bit)
                            _tx_thread_preempted_maps[MAP_INDEX] =  _tx_thread_preempted_maps[MAP_INDEX] | priority_bit;

why 
"TX_MOD32_BIT_SET(next_execute_ptr -> tx_thread_priority, priority_bit)"
not
"TX_MOD32_BIT_SET(thread_ptr -> tx_thread_priority, priority_bit)"?

I think, in that else case _tx_thread_execute_ptr is equal to next_execute_ptr and next_execute_ptr will be scheduled soon, thread_ptr is preempted.

**Comment by goldscott** [comment]
Hi @arm7star - we believe you are correct. Thanks for bringing this up!
How did you find this? Some problem in your code at runtime?

**Comment by arm7star** [comment]
I found it unintentionally when i read the codes. Thank you!

**Comment by goldscott** [comment]
@arm7star - we have fixed this and it will be in our next release. Great find and thank you for your help!

**Comment by goldscott** [comment]
This has been fixed in https://github.com/azure-rtos/threadx/releases/tag/v6.1.6_rel
