### ISSUE TITLE
disabling stack checking before scheduler loop at ARC-EM

### ISSUE THREAD

**Issue by amgross** [azure-rtos/threadx#91]
Hi,
At last release you disabled stack checking before the scheduler loop.
https://github.com/azure-rtos/threadx/blob/b12bd44faaca46dbad4b06cb93a8669c6e36e02a/ports/arc_em/metaware/readme_threadx.txt#L219
https://github.com/azure-rtos/threadx/blob/b12bd44faaca46dbad4b06cb93a8669c6e36e02a/ports/arc_em/metaware/src/tx_thread_schedule.s#L84-L97
this means that if while looping we will get interrupt that is not part of the threadx (not using context save/restore) we won't have stack checking. 
But if first we will get interrupt that is using context save/restore we will get stack checking again:
https://github.com/azure-rtos/threadx/blob/b12bd44faaca46dbad4b06cb93a8669c6e36e02a/ports/arc_em/metaware/src/tx_thread_context_save.s#L199-L211
What is the idea? Don't we want stack checking in interrupts?!

**Comment by andrejm-rtos** [comment]
This has been fixed and it will be available on the October 2021 release of Azure RTOS
