### ISSUE TITLE
Potential corruption of ARMv8 FP registers during context save/restore

### ISSUE THREAD

**Issue by roxma** [azure-rtos/threadx#94]
I believe there's potential corruption issue of ARMv8 FP registers during context save/restore. 

Let's review the example code in `threadx/ports/cortex_a5x/ac6`.
The IRQ entry is defined in `example_build/sample_threadx/el3_vectors.S`

```
irqFirstLevelHandler:
  STP      x29, x30, [sp, #-16]!
  BL       _tx_thread_context_save
  BL       irqHandler
  B        _tx_thread_context_restore  
```

Since `_tx_thread_context_save` doesn't save any of FP registers. If FP registers get modified in `irqHandler`, we may end up with corrupted value of  `q0~q31/fpsr/fpcr`.

**Comment by goldscott** [comment]
Each thread using the FPU hardware needs to call _tx_thread_fp_enable.

**Comment by roxma** [comment]
@goldscott Thanks for your reply.

But **_tx_thread_fp_enable DOES NOT HELP**. 

1. The FP registers are actually saved in _tx_thread_context_restore instead of _tx_thread_context_save. It's assuming that **irqHandler** may use FPU hardware. This is a false assumption.
2. It's hard to decide which thread is using FPU hardware. armclang may use `q0~q31` as normal register  even if you don't use float/double or SIMD explicitly. There's no requirement and specification on this.

**Comment by roxma** [comment]
@goldscott  To demonstrate my previous point, This example shows how armclang 6.6 uses FP register implicitly.

```
+ cat foo.c
struct foo_t {
    int a0;
    int a1;
    int a2;
    int a3;
};

void foo(struct foo_t *p)
{
    p->a0 = 0;
    p->a1 = 0;
    p->a2 = 0;
    p->a3 = 0;
}


+ armclang --target=aarch64-arm-none-eabi -march=armv8-a -Omax -fno-lto -ffreestanding -c foo.c -o foo.o
+ aarch64-linux-gnu-objdump -D foo.o

foo.o:     file format elf64-littleaarch64


Disassembly of section .text.foo:

0000000000000000 <foo>:
   0:	6f00e400 	movi	v0.2d, #0x0
   4:	3d800000 	str	q0, [x0]
   8:	d65f03c0 	ret
```

**Comment by goldscott** [comment]
We originally wrote this with the intent that floating point would not be done in ISRs. I don't think we knew that the compiler would use the VFP registers. 

I suppose you could compile with some option telling the compiler to NOT use VFP registers, or call _tx_thread_fp_enable for every thread.

**Comment by hwmaier** [comment]
Does this affect the gcc compiler as well or only clang? And would the `-mgeneral-regs-only` compiler option avoid this issue?

**Comment by goldscott** [comment]
This likely affects both clang and gcc.

The ```-mgeneral-regs-only``` flag would alleviate the issue.
