### ISSUE TITLE
ThreadX v4.0b and netx v2.1 source code 

### ISSUE THREAD

**Issue by BhuvaHiren** [azure-rtos/threadx#96]
Hi @goldscott @yuxin-azrtos  ,

I want the source code of the thread v4.0b and netxv2.1d. 
But, I can only find the source code from v6.0 onwards.

Can you help for the same.

Thanks,
Hiren

**Comment by goldscott** [comment]
Those versions are 20 years old. We don't have them available. Why do you want them?

**Comment by BhuvaHiren** [comment]
We need to port one project using these versions to STM32 MCU.

**Comment by hhool** [comment]
I need Threadx v4.0 source code too

**Comment by goldscott** [comment]
Hi @BhuvaHiren and @hhool - can you please contact us directly at azure-rtos-support@microsoft.com. Thanks!
