### ISSUE TITLE
How to know if a semaphore is signaled?

### ISSUE THREAD

**Issue by JesusSmarting** [azure-rtos/threadx#97]
I am doing a port of LevelDB and I need to redesign the function WaitForSingleObject(sem1_, INFINITE);

The only thing I need is to know when a ThreadX semaphore is signaled in order to continue the execution and stop waiting.

**Comment by goldscott** [comment]
Something like this: https://docs.microsoft.com/en-us/azure/rtos/threadx/chapter4#tx_semaphore_put_notify
